#lang racket

; Section 1.2.3: Orders of Growth

(require "common.rkt")

;   Exercise 1.14
;   =============
;   
;   Draw the tree illustrating the process generated by the count-change
;   procedure of section [1.2.2] in making change for 11 cents.  What are
;   the orders of growth of the space and number of steps used by this
;   process as the amount to be changed increases?
;   
;   ------------------------------------------------------------------------
;   [Exercise 1.14]: http://sicp-book.com/book-Z-H-11.html#%_thm_1.14
;   [Section 1.2.2]: http://sicp-book.com/book-Z-H-11.html#%_sec_1.2.2
;   1.2.3 Orders of Growth - p44
;   ------------------------------------------------------------------------

(-start- "1.14")

(prn "                     (count-change 11)
                            |
                            |
                         (cc 11 5)
                            |     \\
                            |      \\
                         (cc 11 4)  (cc -39 5)
                            |     \\
                            |      \\
                         (cc 11 3)  (cc -14 4)
                            |     \\
                            |      (cc 1 3)
                            |         |    \\
                            |         |     \\
                            |      (cc 1 2)  (cc -9 3)
                            |         |    \\
                            |         |     \\
                            |      (cc 1 1)  (cc -4 2)
                            |         |    \\
                            |         |     \\
                            |      (cc 1 0)  (cc 0 1)
                            |
                            |
                         (cc 11 2)
                        /         \\
                       /           \\
                      /             \\
                     /               \\
                    /                 \\
                   /                   \\
          (cc 11 1)                     (cc 6 2)
         /   |                          /       \\
        /    |                         /         \\
(cc 11 0)  (cc 10 1)            (cc 6 1)          (cc 1 2)
          /   |                 /  |                 |    \\
         /    |                /   |                 |     \\
(cc 10 0)  (cc 9 1)    (cc 6 0)  (cc 5 1)         (cc 1 1)  (c -4 2)
          /   |                 /   |                |    \\
         /    |                /    |                |     \\
 (cc 9 0) (cc 8 1)     (cc 5 0)  (cc 4 1)         (cc 1 0)  (cc 0 1)
         /   |                  /   |
        /    |                 /    |
(cc 8 0)  (cc 7 1)     (cc 4 0)  (cc 3 1)
         /   |                  /   |
        /    |                 /    |
(cc 7 0)  (cc 6 1)     (cc 3 0)  (cc 2 1)
         /   |                  /   |
        /    |                 /    |
(cc 6 0)  (cc 5 1)     (cc 2 0)  (cc 1 1)
         /   |                  /   |
        /    |                 /    |
(cc 5 0)  (cc 4 1)     (cc 1 0)  (cc 0 1)
         /   |
        /    |
(cc 4 0)  (cc 3 1)
         /   |
        /    |
(cc 3 0)  (cc 2 1)
         /   |
        /    |
(cc 2 0)  (cc 1 1)
         /   |
        /    |
(cc 1 0)  (cc 0 1)


The growth of space is proportional to the total amount, as each
additional cent adds one step to longest branch, that is the branch
making the change only from pennies.

The growth in the total number of steps is exponential.  Each time the
total is increased by 50 there are at least 5 new branches that conatain
at least the existing number of steps (there is a new branch for each
denomination).
")

(--end-- "1.14")

;   ========================================================================
;   
;   Exercise 1.15
;   =============
;   
;   The sine of an angle (specified in radians) can be computed by making
;   use of the approximation sin x ≈ x if x is sufficiently small, and the
;   trigonometric identity
;   
;                 x           x
;   sin x = 3 sin ─  ─ 4 sin³ ─
;                 3           3
;   
;   to reduce the size of the argument of sin.  (For purposes of this
;   exercise an angle is considered "sufficiently small" if its magnitude is
;   not greater than 0.1 radians.) These ideas are incorporated in the
;   following procedures:
;   
;   (define (cube x) (* x x x))
;   (define (p x) (- (* 3 x) (* 4 (cube x))))
;   (define (sine angle)
;      (if (not (> (abs angle) 0.1))
;          angle
;          (p (sine (/ angle 3.0)))))
;   
;   a.  How many times is the procedure p applied when (sine 12.15) is
;   evaluated?
;   
;   b.  What is the order of growth in space and number of steps (as a
;   function of a) used by the process generated by the sine procedure when
;   (sine a) is evaluated?
;   
;   ------------------------------------------------------------------------
;   [Exercise 1.15]: http://sicp-book.com/book-Z-H-11.html#%_thm_1.15
;   1.2.3 Orders of Growth - p44
;   ------------------------------------------------------------------------

(-start- "1.15")

(prn "a: p is called 5 times.  The problem is equivalent to dividing 121.5
by 3 until we have a value less than 1.  3^4 = 81 < 121.  3^5 = 243 > 122.

b: It is logarithmic wrt a.  The growth in space and steps is linear with
respect to the number of calls to 'p', but the number of calls to p is
logarithmic wrt a.")

(--end-- "1.15")

