#lang racket

; Section 1.2.3: Orders of Growth

(require "common.rkt")

;   Exercise 1.14
;   =============
;   
;   Draw the tree illustrating the process generated by the count-change
;   procedure of section [1.2.2] in making change for 11 cents.  What are
;   the orders of growth of the space and number of steps used by this
;   process as the amount to be changed increases?
;   
;   ------------------------------------------------------------------------
;   [Exercise 1.14]: http://sicp-book.com/book-Z-H-11.html#%_thm_1.14
;   [Section 1.2.2]: http://sicp-book.com/book-Z-H-11.html#%_sec_1.2.2
;   1.2.3 Orders of Growth - p44
;   ------------------------------------------------------------------------

(-start- "1.14")



(--end-- "1.14")

;   ========================================================================
;   
;   Exercise 1.15
;   =============
;   
;   The sine of an angle (specified in radians) can be computed by making
;   use of the approximation sin x ≈ x if x is sufficiently small, and the
;   trigonometric identity
;   
;                 x           x
;   sin x = 3 sin ─  ─ 4 sin³ ─
;                 3           3
;   
;   to reduce the size of the argument of sin.  (For purposes of this
;   exercise an angle is considered "sufficiently small" if its magnitude is
;   not greater than 0.1 radians.) These ideas are incorporated in the
;   following procedures:
;   
;   (define (cube x) (* x x x))
;   (define (p x) (- (* 3 x) (* 4 (cube x))))
;   (define (sine angle)
;      (if (not (> (abs angle) 0.1))
;          angle
;          (p (sine (/ angle 3.0)))))
;   
;   a.  How many times is the procedure p applied when (sine 12.15) is
;   evaluated?
;   
;   b.  What is the order of growth in space and number of steps (as a
;   function of a) used by the process generated by the sine procedure when
;   (sine a) is evaluated?
;   
;   ------------------------------------------------------------------------
;   [Exercise 1.15]: http://sicp-book.com/book-Z-H-11.html#%_thm_1.15
;   1.2.3 Orders of Growth - p44
;   ------------------------------------------------------------------------

(-start- "1.15")



(--end-- "1.15")

