#lang racket

; Section 1.2.1: Linear Recursion and Iteration

(require "common.rkt")

;   Exercise 1.9
;   ============
;   
;   Each of the following two procedures defines a method for adding two
;   positive integers in terms of the procedures inc, which increments its
;   argument by 1, and dec, which decrements its argument by 1.
;   
;   (define (+ a b)
;     (if (= a 0)
;         b
;         (inc (+ (dec a) b))))
;   
;   (define (+ a b)
;     (if (= a 0)
;         b
;         (+ (dec a) (inc b))))
;   
;   Using the substitution model, illustrate the process generated by each
;   procedure in evaluating (+ 4 5).  Are these processes iterative or
;   recursive?
;   
;   ------------------------------------------------------------------------
;   [Exercise 1.9]:  http://sicp-book.com/book-Z-H-11.html#%_thm_1.9
;   1.2.1 Linear Recursion and Iteration - p36
;   ------------------------------------------------------------------------

(-start- "1.9")



(--end-- "1.9")

;   ========================================================================
;   
;   Exercise 1.10
;   =============
;   
;   The following procedure computes a mathematical function called
;   Ackermann's function.
;   
;   (define (A x y)
;     (cond ((= y 0) 0)
;           ((= x 0) (* 2 y))
;           ((= y 1) 2)
;           (else (A (- x 1)
;                    (A x (- y 1))))))
;   
;   What are the values of the following expressions?
;   
;   (A 1 10)
;   
;   (A 2 4)
;   
;   (A 3 3)
;   
;   Consider the following procedures, where A is the procedure defined
;   above:
;   
;   (define (f n) (A 0 n))
;   
;   (define (g n) (A 1 n))
;   
;   (define (h n) (A 2 n))
;   
;   (define (k n) (* 5 n n))
;   
;   Give concise mathematical definitions for the functions computed by the
;   procedures f, g, and h for positive integer values of n.  For example,
;   (k n) computes 5n².
;   
;   ------------------------------------------------------------------------
;   [Exercise 1.10]: http://sicp-book.com/book-Z-H-11.html#%_thm_1.10
;   1.2.1 Linear Recursion and Iteration - p36
;   ------------------------------------------------------------------------

(-start- "1.10")



(--end-- "1.10")

